[general]
import = ["~/.config/alacritty/dank-theme.toml"]

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = -1

[cursor]
style = { shape = "Block", blinking = "On" }

[window]
dynamic_title = true
decorations_theme_variant = "Dark"
padding = {x = 6,y = 6}
dynamic_padding = true
