[general]
import = ["~/.config/alacritty/dank-theme.toml"]

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[font]
size = 12.0

[cursor]
style = { shape = "Block", blinking = "On" }
smooth_motion = true
smooth_motion_factor = 0.7
smooth_motion_spring = 0.5
smooth_motion_max_stretch_x = 3.0
smooth_motion_max_stretch_y = 3.0

[window]
dynamic_title = true
decorations_theme_variant = "Dark"
padding = {x = 6,y = 6}
dynamic_padding = true
