theme = "tokyonight_storm"

[editor]
line-number = "relative" # 相对行号
cursor-shape = { insert = "bar", normal = "block", select = "underline" } # 光标
true-color = true 
lsp.display-messages = true
bufferline = "multiple"
auto-format = true # 自动格式化
